
include $(SPECTRUM_ROOT)/makefiles/make.header

TARGET = libdataio.a

FILES = \
	SignatureDatabaseReader.cpp \
	SignatureDatabaseWriter.cpp \
	DiscreteLabelWriter.cpp \
	DiscreteLabelReader.cpp \
	SpectrumReader.cpp \
	SpectrumWriter.cpp \
	QuantityLabelWriter.cpp \
	QuantityLabelReader.cpp \
	SymbolReader.cpp

# knows how to build target and more.
include $(SPECTRUM_ROOT)/makefiles/make.action
# DO NOT DELETE

obj/SignatureDatabaseReader.o: ../COIN/include/CoinError.hpp
obj/SignatureDatabaseReader.o: ../include/SignatureDatabaseReader.h
obj/SignatureDatabaseReader.o: ../include/SignatureDatabase.h
obj/SignatureDatabaseReader.o: ../COIN/include/CoinPackedMatrix.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinFloatEqual.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinFinite.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/SignatureDatabaseReader.o: ../include/Signature.h
obj/SignatureDatabaseReader.o: ../include/SpectrumVector.h
obj/SignatureDatabaseReader.o: ../COIN/include/CoinPackedVector.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinSort.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinDistance.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinError.hpp
obj/SignatureDatabaseWriter.o: ../include/Signature.h
obj/SignatureDatabaseWriter.o: ../include/SpectrumVector.h
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinPackedVector.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinFloatEqual.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinFinite.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinSort.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinDistance.hpp
obj/SignatureDatabaseWriter.o: ../include/SignatureDatabaseWriter.h
obj/SignatureDatabaseWriter.o: ../include/Spectrum.h
obj/SignatureDatabaseWriter.o: ../include/SignatureDatabaseReader.h
obj/SignatureDatabaseWriter.o: ../include/SignatureDatabase.h
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinPackedMatrix.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/DiscreteLabelWriter.o: ../COIN/include/CoinError.hpp
obj/DiscreteLabelWriter.o: ../include/DiscreteLabelWriter.h
obj/DiscreteLabelWriter.o: ../include/DiscreteLabel.h
obj/DiscreteLabelWriter.o: ../include/QuantityLabel.h
obj/DiscreteLabelReader.o: ../include/DiscreteLabel.h
obj/DiscreteLabelReader.o: ../include/QuantityLabel.h
obj/DiscreteLabelReader.o: ../include/DiscreteLabelReader.h
obj/DiscreteLabelReader.o: ../include/DiscreteLabelWriter.h
obj/SpectrumReader.o: ../COIN/include/CoinError.hpp
obj/SpectrumReader.o: ../include/Spectrum.h
obj/SpectrumReader.o: ../COIN/include/CoinPackedVector.hpp
obj/SpectrumReader.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SpectrumReader.o: ../COIN/include/CoinFloatEqual.hpp
obj/SpectrumReader.o: ../COIN/include/CoinFinite.hpp
obj/SpectrumReader.o: ../COIN/include/CoinSort.hpp
obj/SpectrumReader.o: ../COIN/include/CoinDistance.hpp
obj/SpectrumReader.o: ../include/SpectrumVector.h
obj/SpectrumReader.o: ../include/SpectrumReader.h
obj/SpectrumWriter.o: ../COIN/include/CoinError.hpp
obj/SpectrumWriter.o: ../include/Spectrum.h
obj/SpectrumWriter.o: ../COIN/include/CoinPackedVector.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinFloatEqual.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinFinite.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinSort.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinDistance.hpp
obj/SpectrumWriter.o: ../include/SpectrumVector.h
obj/SpectrumWriter.o: ../include/SpectrumReader.h
obj/SpectrumWriter.o: ../include/SpectrumWriter.h
obj/QuantityLabelWriter.o: ../COIN/include/CoinError.hpp
obj/QuantityLabelWriter.o: ../include/Signature.h
obj/QuantityLabelWriter.o: ../include/SpectrumVector.h
obj/QuantityLabelWriter.o: ../COIN/include/CoinPackedVector.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinFloatEqual.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinFinite.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinSort.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinDistance.hpp
obj/QuantityLabelWriter.o: ../include/QuantityLabelWriter.h
obj/QuantityLabelWriter.o: ../include/DiscreteLabel.h
obj/QuantityLabelWriter.o: ../include/QuantityLabel.h
obj/QuantityLabelWriter.o: ../include/DiscreteLabelWriter.h
obj/QuantityLabelWriter.o: ../include/SignatureDatabase.h
obj/QuantityLabelWriter.o: ../COIN/include/CoinPackedMatrix.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/QuantityLabelReader.o: ../include/QuantityLabel.h
obj/QuantityLabelReader.o: ../include/QuantityLabelReader.h
obj/QuantityLabelReader.o: ../include/DiscreteLabelWriter.h
obj/QuantityLabelReader.o: ../include/DiscreteLabel.h
obj/SymbolReader.o: ../include/SymbolReader.h
obj/SymbolReader.o: ../include/Symbol.h
