
include $(SPECTRUM_ROOT)/makefiles/make.header

TARGET = libdataio.a

FILES = \
	SignatureDatabaseReader.cpp \
	SignatureDatabaseWriter.cpp \
	DiscreteLabelWriter.cpp \
	DiscreteLabelReader.cpp \
	SpectrumReader.cpp \
	SpectrumWriter.cpp \
	QuantityLabelWriter.cpp \
	QuantityLabelReader.cpp \
	SymbolReader.cpp

# knows how to build target and more.
include $(SPECTRUM_ROOT)/makefiles/make.action
# DO NOT DELETE

obj/SignatureDatabaseReader.o: ../COIN/include/CoinError.hpp
obj/SignatureDatabaseReader.o: ../include/SignatureDatabaseReader.h
obj/SignatureDatabaseReader.o: ../include/SignatureDatabase.h
obj/SignatureDatabaseReader.o: ../COIN/include/CoinPackedMatrix.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinFloatEqual.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinFinite.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/SignatureDatabaseReader.o: ../include/Signature.h
obj/SignatureDatabaseReader.o: ../include/SpectrumVector.h
obj/SignatureDatabaseReader.o: ../COIN/include/CoinPackedVector.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinSort.hpp
obj/SignatureDatabaseReader.o: ../COIN/include/CoinDistance.hpp
obj/SignatureDatabaseReader.o: /usr/include/string.h /usr/include/features.h
obj/SignatureDatabaseReader.o: /usr/include/sys/cdefs.h
obj/SignatureDatabaseReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/SignatureDatabaseReader.o: /usr/include/assert.h
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinError.hpp
obj/SignatureDatabaseWriter.o: ../include/Signature.h
obj/SignatureDatabaseWriter.o: ../include/SpectrumVector.h
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinPackedVector.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinFloatEqual.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinFinite.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinSort.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinDistance.hpp
obj/SignatureDatabaseWriter.o: ../include/SignatureDatabaseWriter.h
obj/SignatureDatabaseWriter.o: ../include/Spectrum.h
obj/SignatureDatabaseWriter.o: ../include/SignatureDatabaseReader.h
obj/SignatureDatabaseWriter.o: ../include/SignatureDatabase.h
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinPackedMatrix.hpp
obj/SignatureDatabaseWriter.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/SignatureDatabaseWriter.o: /usr/include/string.h /usr/include/features.h
obj/SignatureDatabaseWriter.o: /usr/include/sys/cdefs.h
obj/SignatureDatabaseWriter.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/DiscreteLabelWriter.o: ../COIN/include/CoinError.hpp
obj/DiscreteLabelWriter.o: ../include/DiscreteLabelWriter.h
obj/DiscreteLabelWriter.o: ../include/DiscreteLabel.h
obj/DiscreteLabelWriter.o: /usr/include/stdlib.h /usr/include/features.h
obj/DiscreteLabelWriter.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/DiscreteLabelWriter.o: ../include/QuantityLabel.h
obj/DiscreteLabelWriter.o: /usr/include/string.h /usr/include/stdio.h
obj/DiscreteLabelWriter.o: /usr/include/bits/types.h
obj/DiscreteLabelWriter.o: /usr/include/bits/wordsize.h
obj/DiscreteLabelWriter.o: /usr/include/bits/typesizes.h /usr/include/libio.h
obj/DiscreteLabelWriter.o: /usr/include/_G_config.h /usr/include/wchar.h
obj/DiscreteLabelWriter.o: /usr/include/bits/wchar.h /usr/include/gconv.h
obj/DiscreteLabelWriter.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stdarg.h
obj/DiscreteLabelWriter.o: /usr/include/bits/stdio_lim.h
obj/DiscreteLabelWriter.o: /usr/include/bits/sys_errlist.h
obj/DiscreteLabelReader.o: ../include/DiscreteLabel.h
obj/DiscreteLabelReader.o: /usr/include/stdlib.h /usr/include/features.h
obj/DiscreteLabelReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/DiscreteLabelReader.o: ../include/QuantityLabel.h
obj/DiscreteLabelReader.o: /usr/include/string.h
obj/DiscreteLabelReader.o: ../include/DiscreteLabelReader.h
obj/DiscreteLabelReader.o: ../include/DiscreteLabelWriter.h
obj/DiscreteLabelReader.o: /usr/include/stdio.h /usr/include/bits/types.h
obj/DiscreteLabelReader.o: /usr/include/bits/wordsize.h
obj/DiscreteLabelReader.o: /usr/include/bits/typesizes.h /usr/include/libio.h
obj/DiscreteLabelReader.o: /usr/include/_G_config.h /usr/include/wchar.h
obj/DiscreteLabelReader.o: /usr/include/bits/wchar.h /usr/include/gconv.h
obj/DiscreteLabelReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stdarg.h
obj/DiscreteLabelReader.o: /usr/include/bits/stdio_lim.h
obj/DiscreteLabelReader.o: /usr/include/bits/sys_errlist.h
obj/DiscreteLabelReader.o: /usr/include/assert.h
obj/SpectrumReader.o: ../COIN/include/CoinError.hpp
obj/SpectrumReader.o: ../include/Spectrum.h
obj/SpectrumReader.o: ../COIN/include/CoinPackedVector.hpp
obj/SpectrumReader.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SpectrumReader.o: ../COIN/include/CoinFloatEqual.hpp
obj/SpectrumReader.o: ../COIN/include/CoinFinite.hpp
obj/SpectrumReader.o: ../COIN/include/CoinSort.hpp
obj/SpectrumReader.o: ../COIN/include/CoinDistance.hpp
obj/SpectrumReader.o: ../include/SpectrumVector.h
obj/SpectrumReader.o: ../include/SpectrumReader.h
obj/SpectrumReader.o: /usr/include/assert.h /usr/include/features.h
obj/SpectrumReader.o: /usr/include/string.h
obj/SpectrumReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/SpectrumWriter.o: ../COIN/include/CoinError.hpp
obj/SpectrumWriter.o: ../include/Spectrum.h
obj/SpectrumWriter.o: ../COIN/include/CoinPackedVector.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinFloatEqual.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinFinite.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinSort.hpp
obj/SpectrumWriter.o: ../COIN/include/CoinDistance.hpp
obj/SpectrumWriter.o: ../include/SpectrumVector.h
obj/SpectrumWriter.o: ../include/SpectrumReader.h
obj/SpectrumWriter.o: ../include/SpectrumWriter.h
obj/SpectrumWriter.o: /usr/include/string.h /usr/include/features.h
obj/SpectrumWriter.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/QuantityLabelWriter.o: ../COIN/include/CoinError.hpp
obj/QuantityLabelWriter.o: ../include/Signature.h
obj/QuantityLabelWriter.o: ../include/SpectrumVector.h
obj/QuantityLabelWriter.o: ../COIN/include/CoinPackedVector.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinFloatEqual.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinFinite.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinSort.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinDistance.hpp
obj/QuantityLabelWriter.o: ../include/QuantityLabelWriter.h
obj/QuantityLabelWriter.o: ../include/DiscreteLabel.h
obj/QuantityLabelWriter.o: /usr/include/stdlib.h /usr/include/features.h
obj/QuantityLabelWriter.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/QuantityLabelWriter.o: ../include/QuantityLabel.h
obj/QuantityLabelWriter.o: /usr/include/string.h
obj/QuantityLabelWriter.o: ../include/DiscreteLabelWriter.h
obj/QuantityLabelWriter.o: /usr/include/stdio.h /usr/include/bits/types.h
obj/QuantityLabelWriter.o: /usr/include/bits/wordsize.h
obj/QuantityLabelWriter.o: /usr/include/bits/typesizes.h /usr/include/libio.h
obj/QuantityLabelWriter.o: /usr/include/_G_config.h /usr/include/wchar.h
obj/QuantityLabelWriter.o: /usr/include/bits/wchar.h /usr/include/gconv.h
obj/QuantityLabelWriter.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stdarg.h
obj/QuantityLabelWriter.o: /usr/include/bits/stdio_lim.h
obj/QuantityLabelWriter.o: /usr/include/bits/sys_errlist.h
obj/QuantityLabelWriter.o: ../include/SignatureDatabase.h
obj/QuantityLabelWriter.o: ../COIN/include/CoinPackedMatrix.hpp
obj/QuantityLabelWriter.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/QuantityLabelReader.o: ../include/QuantityLabel.h
obj/QuantityLabelReader.o: /usr/include/stdlib.h /usr/include/features.h
obj/QuantityLabelReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/QuantityLabelReader.o: /usr/include/string.h
obj/QuantityLabelReader.o: ../include/QuantityLabelReader.h
obj/QuantityLabelReader.o: ../include/DiscreteLabelWriter.h
obj/QuantityLabelReader.o: ../include/DiscreteLabel.h
obj/QuantityLabelReader.o: /usr/include/stdio.h /usr/include/bits/types.h
obj/QuantityLabelReader.o: /usr/include/bits/wordsize.h
obj/QuantityLabelReader.o: /usr/include/bits/typesizes.h /usr/include/libio.h
obj/QuantityLabelReader.o: /usr/include/_G_config.h /usr/include/wchar.h
obj/QuantityLabelReader.o: /usr/include/bits/wchar.h /usr/include/gconv.h
obj/QuantityLabelReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stdarg.h
obj/QuantityLabelReader.o: /usr/include/bits/stdio_lim.h
obj/QuantityLabelReader.o: /usr/include/bits/sys_errlist.h
obj/QuantityLabelReader.o: /usr/include/assert.h
obj/SymbolReader.o: ../include/SymbolReader.h
obj/SymbolReader.o: ../include/Symbol.h
obj/SymbolReader.o: /usr/include/stdio.h /usr/include/features.h
obj/SymbolReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/SymbolReader.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
obj/SymbolReader.o: /usr/include/bits/typesizes.h /usr/include/libio.h
obj/SymbolReader.o: /usr/include/_G_config.h /usr/include/wchar.h
obj/SymbolReader.o: /usr/include/bits/wchar.h /usr/include/gconv.h
obj/SymbolReader.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stdarg.h
obj/SymbolReader.o: /usr/include/bits/stdio_lim.h
obj/SymbolReader.o: /usr/include/bits/sys_errlist.h /usr/include/string.h
