
include $(SPECTRUM_ROOT)/makefiles/make.header

TARGET = libdatagen.a

FILES = \
	DatasetGenerator.cpp \
	SignatureGenerator.cpp \
	SignatureFileGenerator.cpp 
	
# knows how to build target and more.
include $(SPECTRUM_ROOT)/makefiles/make.action
# DO NOT DELETE

obj/DatasetGenerator.o: ../include/DatasetGenerator.h
obj/DatasetGenerator.o: ../include/Signature.h
obj/DatasetGenerator.o: ../include/SpectrumVector.h
obj/DatasetGenerator.o: ../COIN/include/CoinPackedVector.hpp
obj/DatasetGenerator.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/DatasetGenerator.o: ../COIN/include/CoinError.hpp
obj/DatasetGenerator.o: ../COIN/include/CoinFloatEqual.hpp
obj/DatasetGenerator.o: ../COIN/include/CoinFinite.hpp
obj/DatasetGenerator.o: ../COIN/include/CoinSort.hpp
obj/DatasetGenerator.o: ../COIN/include/CoinDistance.hpp
obj/DatasetGenerator.o: ../include/SignatureDatabaseReader.h
obj/DatasetGenerator.o: ../include/SignatureDatabase.h
obj/DatasetGenerator.o: ../COIN/include/CoinPackedMatrix.hpp
obj/DatasetGenerator.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/DatasetGenerator.o: ../include/SignatureDatabaseWriter.h
obj/DatasetGenerator.o: ../include/Spectrum.h
obj/DatasetGenerator.o: ../include/SpectrumReader.h
obj/DatasetGenerator.o: ../include/SpectrumWriter.h
obj/DatasetGenerator.o: ../include/DiscreteLabel.h
obj/DatasetGenerator.o: /usr/include/stdlib.h /usr/include/features.h
obj/DatasetGenerator.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/DatasetGenerator.o: ../include/QuantityLabel.h
obj/DatasetGenerator.o: /usr/include/string.h
obj/DatasetGenerator.o: ../include/DiscreteLabelWriter.h
obj/DatasetGenerator.o: /usr/include/stdio.h /usr/include/bits/types.h
obj/DatasetGenerator.o: /usr/include/bits/wordsize.h
obj/DatasetGenerator.o: /usr/include/bits/typesizes.h /usr/include/libio.h
obj/DatasetGenerator.o: /usr/include/_G_config.h /usr/include/wchar.h
obj/DatasetGenerator.o: /usr/include/bits/wchar.h /usr/include/gconv.h
obj/DatasetGenerator.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stdarg.h
obj/DatasetGenerator.o: /usr/include/bits/stdio_lim.h
obj/DatasetGenerator.o: /usr/include/bits/sys_errlist.h
obj/DatasetGenerator.o: ../include/QuantityLabelWriter.h
obj/SignatureGenerator.o: ../include/SignatureGenerator.h
obj/SignatureGenerator.o: ../include/Signature.h
obj/SignatureGenerator.o: ../include/SpectrumVector.h
obj/SignatureGenerator.o: ../COIN/include/CoinPackedVector.hpp
obj/SignatureGenerator.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SignatureGenerator.o: ../COIN/include/CoinError.hpp
obj/SignatureGenerator.o: ../COIN/include/CoinFloatEqual.hpp
obj/SignatureGenerator.o: ../COIN/include/CoinFinite.hpp
obj/SignatureGenerator.o: ../COIN/include/CoinSort.hpp
obj/SignatureGenerator.o: ../COIN/include/CoinDistance.hpp
obj/SignatureGenerator.o: ../include/SignatureDatabase.h
obj/SignatureGenerator.o: ../COIN/include/CoinPackedMatrix.hpp
obj/SignatureGenerator.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/SignatureGenerator.o: ../include/Symbol.h
obj/SignatureGenerator.o: /usr/include/math.h /usr/include/features.h
obj/SignatureGenerator.o: /usr/include/bits/huge_val.h
obj/SignatureGenerator.o: /usr/include/bits/mathdef.h
obj/SignatureGenerator.o: /usr/include/bits/mathcalls.h
obj/SignatureFileGenerator.o: ../include/SignatureFileGenerator.h
obj/SignatureFileGenerator.o: ../include/Signature.h
obj/SignatureFileGenerator.o: ../include/SpectrumVector.h
obj/SignatureFileGenerator.o: ../COIN/include/CoinPackedVector.hpp
obj/SignatureFileGenerator.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SignatureFileGenerator.o: ../COIN/include/CoinError.hpp
obj/SignatureFileGenerator.o: ../COIN/include/CoinFloatEqual.hpp
obj/SignatureFileGenerator.o: ../COIN/include/CoinFinite.hpp
obj/SignatureFileGenerator.o: ../COIN/include/CoinSort.hpp
obj/SignatureFileGenerator.o: ../COIN/include/CoinDistance.hpp
obj/SignatureFileGenerator.o: ../include/SignatureGenerator.h
obj/SignatureFileGenerator.o: ../include/SignatureDatabase.h
obj/SignatureFileGenerator.o: ../COIN/include/CoinPackedMatrix.hpp
obj/SignatureFileGenerator.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/SignatureFileGenerator.o: ../include/Symbol.h
obj/SignatureFileGenerator.o: ../include/SignatureDatabaseReader.h
obj/SignatureFileGenerator.o: ../include/SymbolReader.h
obj/SignatureFileGenerator.o: /usr/include/stdio.h /usr/include/features.h
obj/SignatureFileGenerator.o: /usr/include/sys/cdefs.h
obj/SignatureFileGenerator.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/SignatureFileGenerator.o: /usr/include/bits/types.h
obj/SignatureFileGenerator.o: /usr/include/bits/wordsize.h
obj/SignatureFileGenerator.o: /usr/include/bits/typesizes.h
obj/SignatureFileGenerator.o: /usr/include/libio.h /usr/include/_G_config.h
obj/SignatureFileGenerator.o: /usr/include/wchar.h /usr/include/bits/wchar.h
obj/SignatureFileGenerator.o: /usr/include/gconv.h
obj/SignatureFileGenerator.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stdarg.h
obj/SignatureFileGenerator.o: /usr/include/bits/stdio_lim.h
obj/SignatureFileGenerator.o: /usr/include/bits/sys_errlist.h
