
include $(SPECTRUM_ROOT)/makefiles/make.header

TARGET = libtests.a

FILES = \
#	IOTester.C \
#	Tester.C \
#	ManLabelTester.C \
#	DiscreteLabelTester.C \
#	BBTester.C \
#	TopKTester.C \
#	GeneralTester.C \
#	CrawlTester.C \
#	BreadthTester.C \
#	SimpleGroupTester.C

# knows how to build target and more.
include $(SPECTRUM_ROOT)/makefiles/make.action
# DO NOT DELETE
