
include $(SPECTRUM_ROOT)/makefiles/make.header

TARGET = libdatatype.a

FILES = \
        Tile.cpp \
        SpectrumVector.cpp \
        Spectrum.cpp \
	Signature.cpp \
	SignatureDatabase.cpp \
	DiscreteLabel.cpp \
	QuantityLabel.cpp \
	Symbol.cpp

# knows how to build target and more.
include $(SPECTRUM_ROOT)/makefiles/make.action
# DO NOT DELETE

obj/Tile.o: /usr/include/stdlib.h /usr/include/features.h
obj/Tile.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/Tile.o: ../include/Tile.h
obj/SpectrumVector.o: ../include/SpectrumVector.h
obj/SpectrumVector.o: ../COIN/include/CoinPackedVector.hpp
obj/SpectrumVector.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SpectrumVector.o: ../COIN/include/CoinError.hpp
obj/SpectrumVector.o: ../COIN/include/CoinFloatEqual.hpp
obj/SpectrumVector.o: ../COIN/include/CoinFinite.hpp
obj/SpectrumVector.o: ../COIN/include/CoinSort.hpp
obj/SpectrumVector.o: ../COIN/include/CoinDistance.hpp
obj/Spectrum.o: ../include/Spectrum.h
obj/Spectrum.o: ../COIN/include/CoinPackedVector.hpp
obj/Spectrum.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/Spectrum.o: ../COIN/include/CoinError.hpp
obj/Spectrum.o: ../COIN/include/CoinFloatEqual.hpp
obj/Spectrum.o: ../COIN/include/CoinFinite.hpp ../COIN/include/CoinSort.hpp
obj/Spectrum.o: ../COIN/include/CoinDistance.hpp
obj/Spectrum.o: ../include/SpectrumVector.h
obj/Signature.o: ../include/Signature.h
obj/Signature.o: ../include/SpectrumVector.h
obj/Signature.o: ../COIN/include/CoinPackedVector.hpp
obj/Signature.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/Signature.o: ../COIN/include/CoinError.hpp
obj/Signature.o: ../COIN/include/CoinFloatEqual.hpp
obj/Signature.o: ../COIN/include/CoinFinite.hpp ../COIN/include/CoinSort.hpp
obj/Signature.o: ../COIN/include/CoinDistance.hpp
obj/SignatureDatabase.o: ../include/SignatureDatabase.h
obj/SignatureDatabase.o: ../COIN/include/CoinPackedMatrix.hpp
obj/SignatureDatabase.o: ../COIN/include/CoinError.hpp
obj/SignatureDatabase.o: ../COIN/include/CoinPackedVectorBase.hpp
obj/SignatureDatabase.o: ../COIN/include/CoinFloatEqual.hpp
obj/SignatureDatabase.o: ../COIN/include/CoinFinite.hpp
obj/SignatureDatabase.o: ../COIN/include/CoinShallowPackedVector.hpp
obj/SignatureDatabase.o: ../include/Signature.h
obj/SignatureDatabase.o: ../include/SpectrumVector.h
obj/SignatureDatabase.o: ../COIN/include/CoinPackedVector.hpp
obj/SignatureDatabase.o: ../COIN/include/CoinSort.hpp
obj/SignatureDatabase.o: ../COIN/include/CoinDistance.hpp
obj/DiscreteLabel.o: ../include/DiscreteLabel.h
obj/DiscreteLabel.o: /usr/include/stdlib.h /usr/include/features.h
obj/DiscreteLabel.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/DiscreteLabel.o: ../include/QuantityLabel.h
obj/DiscreteLabel.o: /usr/include/string.h
obj/QuantityLabel.o: ../include/QuantityLabel.h
obj/QuantityLabel.o: /usr/include/stdlib.h /usr/include/features.h
obj/QuantityLabel.o: /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/include/stddef.h
obj/QuantityLabel.o: /usr/include/string.h
obj/Symbol.o: ../include/Symbol.h
